language: node_js
node_js:
  - 'stable'
os: osx
jobs:
  # allow_failures:
  #   - os: osx
  fast_finish: true
install:
  - npm install
script:
  npm run test:app
  # safelist
  # branches:
  #   only:
  #     - master
  #     - middleware
  #     - chronosWebsite
