version: '1'
services:
  frontend:
    # Use image built from the Dockerfile in /frontend dir.
    build: './frontend'

    container_name: 'frontend'

    # Bind container and host machine to exposed port, 3000.
    # ports:
    #   - '3000:3000'

    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  books:
    build: './books'

    container_name: 'books'

    ports:
      - '8888:8888'

    depends_on:
      - frontend

    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'


