version: "3"
services:
  test: 
    image: sg55/mm-dev-chronos:1.0
    container_name: 'mm-test'
    ports:
      - 8080:8080
    volumes:
      - ".:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
    command: npm run test
    depends_on:
      - postgres-db-test
  postgres-db-test:
    image: sg55/mm-postgres-chronos:1.0
    container_name: 'mm-test-database'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=mmadmin
      - POSTGRES_DB=mmdb=value
    volumes:
      - test-db-volume:/var/lib/postgresql/data
volumes:
  node_modules:
  test-db-volume:
    
